{% set name = "pika" %}
{% set version = "0.13.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: pika-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pika/pika-{{ version }}.tar.gz
  sha256: 5338d829d1edb3e5bcf1523b4a9e32c56dea5a8bda7018825849e35325580484

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pika

about:
  home: https://pika.readthedocs.io
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Pure Python RabbitMQ/AMQP 0-9-1 client library
  doc_url: https://pika.readthedocs.io
  dev_url: https://github.com/pika/pika

extra:
  recipe-maintainers:
    - frol
    - ltalirz
