{% set name = "pika" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: pika-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pika/pika-{{ version }}.tar.gz
  sha256: 9fa76ba4b65034b878b2b8de90ff8660a59d925b087c5bb88f8fdbb4b64a1dbf

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pika

about:
  home: https://pika.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Pure Python RabbitMQ/AMQP 0-9-1 client library
  doc_url: https://pika.readthedocs.io
  dev_url: https://github.com/pika/pika

extra:
  recipe-maintainers:
    - frol
    - ltalirz
